//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACATExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACATExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2013-15 Intel Corporation.\nAll rights reserved..
        /// </summary>
        internal static string AssemblyCopyright {
            get {
                return ResourceManager.GetString("AssemblyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Talk Window?.
        /// </summary>
        internal static string ClearTalkWindow {
            get {
                return ResourceManager.GetString("ClearTalkWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the highlighted window?.
        /// </summary>
        internal static string CloseTheHighlightedWindow {
            get {
                return ResourceManager.GetString("CloseTheHighlightedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Send?.
        /// </summary>
        internal static string ConfirmSend {
            get {
                return ResourceManager.GetString("ConfirmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English UI provided by Intel.
        /// </summary>
        internal static string CurrentLanguageAttribution {
            get {
                return ResourceManager.GetString("CurrentLanguageAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is empty.
        /// </summary>
        internal static string DocumentIsEmpty {
            get {
                return ResourceManager.GetString("DocumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Clipboard.
        /// </summary>
        internal static string ExplorerClipboard {
            get {
                return ResourceManager.GetString("ExplorerClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer File Ops.
        /// </summary>
        internal static string ExplorerFileOps {
            get {
                return ResourceManager.GetString("ExplorerFileOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Navigate.
        /// </summary>
        internal static string ExplorerNavigate {
            get {
                return ResourceManager.GetString("ExplorerNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture Manager.
        /// </summary>
        internal static string LectureManager {
            get {
                return ResourceManager.GetString("LectureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this document into Lecture Manager?.
        /// </summary>
        internal static string LoadThisDocumentIntoLectureManager {
            get {
                return ResourceManager.GetString("LoadThisDocumentIntoLectureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multilanguage User Interface (localization) developed by Bruno Lima (bruno.lima@live.com). If you need help translating ACAT, just send an e-mail..
        /// </summary>
        internal static string LocalizationAttribution {
            get {
                return ResourceManager.GetString("LocalizationAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the screen?.
        /// </summary>
        internal static string LockTheScreen {
            get {
                return ResourceManager.GetString("LockTheScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Application?.
        /// </summary>
        internal static string QuitApplication {
            get {
                return ResourceManager.GetString("QuitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Font Setting?.
        /// </summary>
        internal static string SaveFontSetting {
            get {
                return ResourceManager.GetString("SaveFontSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version0 {
            get {
                return ResourceManager.GetString("Version0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
