//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbbreviationsAgent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbbreviationsAgent.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t-------- ABBREVIATIONS LIST EMPTY --------.
        /// </summary>
        internal static string _TABBREVIATIONSLISTEMPTY {
            get {
                return ResourceManager.GetString("_TABBREVIATIONSLISTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new abbreviation?.
        /// </summary>
        internal static string AddNewAbbreviation {
            get {
                return ResourceManager.GetString("AddNewAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and Quit?.
        /// </summary>
        internal static string CancelAndQuit {
            get {
                return ResourceManager.GetString("CancelAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Save. Abbr for &apos;{0}&apos; already exists.
        /// </summary>
        internal static string CantSaveAbbrFor0AlreadyExists {
            get {
                return ResourceManager.GetString("CantSaveAbbrFor0AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter?.
        /// </summary>
        internal static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close?.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string Delete0 {
            get {
                return ResourceManager.GetString("Delete0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion is empty.
        /// </summary>
        internal static string ExpansionIsEmpty {
            get {
                return ResourceManager.GetString("ExpansionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string Page0Of1 {
            get {
                return ResourceManager.GetString("Page0Of1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an abbreviation!.
        /// </summary>
        internal static string PleaseEnterAnAbbreviation {
            get {
                return ResourceManager.GetString("PleaseEnterAnAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Abbreviation and Quit?.
        /// </summary>
        internal static string SaveAbbreviationAndQuit {
            get {
                return ResourceManager.GetString("SaveAbbreviationAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order:  ALPHABETICAL.
        /// </summary>
        internal static string SortOrderALPHABETICAL {
            get {
                return ResourceManager.GetString("SortOrderALPHABETICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order:  REVERSE ALPHABETICAL.
        /// </summary>
        internal static string SortOrderREVERSEALPHABETICAL {
            get {
                return ResourceManager.GetString("SortOrderREVERSEALPHABETICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are changing existing abbr {0} . Continue?.
        /// </summary>
        internal static string YouAreChangingExistingAbbr0Continue {
            get {
                return ResourceManager.GetString("YouAreChangingExistingAbbr0Continue", resourceCulture);
            }
        }
    }
}
